list:
  just --list

printh-bmark:
  gcc -o printh-bmark printh-bmark.c ../info/printh.c

bashgen-bmark:
  gcc -o bashgen-bmark bashgen-bmark.c ../automation/bashgen.c

zshgen-bmark:
  gcc -o zshgen-bmark zshgen-bmark.c ../automation/zshgen.c

bashgen-zshgen-printh-bmark:
  gcc -o bashgen-zshgen-printh-bmark bashgen-zshgen-printh-bmark.c ../info/printh.c ../automation/bashgen.c ../automation/zshgen.c

heap_string_test:
  gcc ./memory/heap/heap_string_test.c ../memory/heap/heap_alloc.c ../memory/heap/heap_string.c -I../memory/heap/
