list:
  just --list

printh-bmark:
  gcc -o printh-bmark printh-bmark.c ../info/printh.c

bashgen-bmark:
  gcc -o bashgen-bmark bashgen-bmark.c ../automation/bashgen.c

zshgen-bmark:
  gcc -o zshgen-bmark zshgen-bmark.c ../automation/zshgen.c
