all: printh-bmark bashgen-zshgen-printh-bmark bashgen-bmark zshgen-bmark heap_string_test

list:
  just --list

printh-bmark:
  gcc -o printh-bmark ./info/printh-bmark.c ../info/printh.c -I../info/

bashgen-bmark:
  gcc -o bashgen-bmark ./automation/bashgen-bmark.c ../automation/bashgen.c -I../automation/

zshgen-bmark:
  gcc -o zshgen-bmark ./automation/zshgen-bmark.c ../automation/zshgen.c -I../automation/

bashgen-zshgen-printh-bmark:
  gcc -o bashgen-zshgen-printh-bmark ./automation/bashgen-zshgen-printh-bmark.c ../info/printh.c ../automation/bashgen.c ../automation/zshgen.c -I../automation/ -I../info/

heap_string_test:
  gcc ./heap/heap_string_test.c ../heap/heap_alloc.c ../heap/heap_string.c -I../heap/
