E(CharNotFound, "character not found")
E(BufferTooSmall, "buffer size is too small")
E(ValueNotFound, "value not found")
E(DelimiterNotFound, "delimiter not found")
E(OutOfBounds, "out of bounds access attempt")
E(ElementIsEmpty, "element is empty")
E(IndexNoExist, "index doesn't exist")
E(MaxCapacityReached, "maximum capacity has been reached")
E(NothingToDo, "nothing to do")
E(IncompatibleTypes, "incompatible types")
